name: gen-index-json-github-action
run-name: ${{ github.actor }} is running GitHub Actions
on: [push]
jobs:
  gen-index-json:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Run a ruby script
        run: ruby lib/gen_index_json.rb
      # - uses: EndBug/add-and-commit@v9.1.4
      #   with:
      #     add: 'posts'
      #     author_name: Heaven's the Jack
      #     author_email: heavens.the.jack@gmail.com
      #     commit: --signoff
      #     committer_name: Heaven's the Jack
      #     committer_email: heavens.the.jack@gmail.com
      #     fetch: false
      #     message: 'Update posts/index.json'
