name: gen-index-json-github-action
run-name: ${{ github.actor }} is running GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  gen-index-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Run a ruby script
        run: ruby lib/gen_index_json.rb

      - uses: EndBug/add-and-commit@v9.1.4
        with:
          add: 'posts'
          # author_name: heavens-the-jack
          # author_email: heavens.the.jack@gmail.com
          # commit: --signoff
          # committer_name: heavens-the-jack
          # committer_email: heavens.the.jack@gmail.com
          # fetch: false
          message: 'Update posts/index.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

