name: gen-index-json-github-action
run-name: ${{ github.actor }} is running gen-index-json-github-action

on:
  push:
    branches:
      - main

jobs:
  gen-index-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Run a ruby script
        run: ruby lib/gen_index_json.rb

      - uses: EndBug/add-and-commit@v9.1.4
        with:
          add: 'posts'
          message: 'Update posts/index.json'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
